version: 0.1
phases:
    install:
        runtime-versions:
            python: 2.7
            Django 1.9
        commands:
            virtualenv venv
            source ./venv/bin/activate
            pip install -r requirements
            # Install dependencies needed for running the static analysis
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
